action:
  parameters:
    skip_dependencies: '{{ config_context.skip_dependencies_on_install }}'
    trigger_payload: '{{ trigger }}'
  ref: bitovi_packs.handle_pack_commit
description: 'Watch for file changes and trigger action to reinstall packs when the
  git commit hash changes'
enabled: true
name: watch_pack_commit
trigger:
  parameters:
    file_path: /opt/stackstorm/bitovi-stackstorm-exchange/bitovi_chatops/.git/logs/refs/heads/dev
  type: linux.file_watch.line
